package arthur.geradordenumerosdamegasena;

import java.util.Random;

/**
 *
 * @author Gasparzinho
 */
public class TelaProjeto extends javax.swing.JFrame {    
                         
    //Atributos para manipular os componentes da tela
    private javax.swing.JButton gerarNumeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JTextField numero3;
    private javax.swing.JTextField numero4;
    private javax.swing.JTextField numero5;
    private javax.swing.JTextField numero6;
    
    //atributos criados para gerar numeros aleatorios e armazenar no vetor
    private Random gerador = new Random();
    private int[] numeros = new int[6];
    
    //Construtor para inicializar os componentes
    public TelaProjeto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                              
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        numero1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gerarNumeros = new javax.swing.JButton();
        numero2 = new javax.swing.JTextField();
        numero3 = new javax.swing.JTextField();
        numero4 = new javax.swing.JTextField();
        numero5 = new javax.swing.JTextField();
        numero6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        numero1.setEditable(false);
        numero1.setBackground(new java.awt.Color(255, 255, 255));
        numero1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerador De Números Da Mega Sena");

        gerarNumeros.setText("Gerar Números");
        gerarNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarNumerosActionPerformed(evt);
            }
        });

        numero2.setEditable(false);
        numero2.setBackground(new java.awt.Color(255, 255, 255));
        numero2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numero3.setEditable(false);
        numero3.setBackground(new java.awt.Color(255, 255, 255));
        numero3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numero4.setEditable(false);
        numero4.setBackground(new java.awt.Color(255, 255, 255));
        numero4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numero5.setEditable(false);
        numero5.setBackground(new java.awt.Color(255, 255, 255));
        numero5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        numero6.setEditable(false);
        numero6.setBackground(new java.awt.Color(255, 255, 255));
        numero6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(gerarNumeros)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(gerarNumeros)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>
    
    
    //Método usado quando o botão gerar for acionado, chama os métodos criados
    private void gerarNumerosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        gerarNumeros.setEnabled(false);
        this.sorteioNumerico();
        this.setaValoresNasSaidas();
        gerarNumeros.setEnabled(true);
    }
    
    //Método criado para setar os valores gerados nos campos de saida
    private void setaValoresNasSaidas(){
        numero1.setText(""+ numeros[0]);
        numero2.setText(""+ numeros[1]);
        numero3.setText(""+ numeros[2]);
        numero4.setText(""+ numeros[3]);
        numero5.setText(""+ numeros[4]);
        numero6.setText(""+ numeros[5]);
    }
    
    /*
        Método criado para salvar os valores no vetor
    */
    private void sorteioNumerico(){
        int posicaoVetor = 0;
        int valorSorteado;
        int verificacao;
        
        while(posicaoVetor < 6){
            
            valorSorteado = this.geraNumeros();
            verificacao = this.verificaNumerosRepetidos(valorSorteado);
            
            //Caso o valor seja 0, como não existe o valor 0 na mega sena, ele passa a ser 1
            if(valorSorteado == 0){
                valorSorteado++;
            }
            
            if(verificacao == 0){
                numeros[posicaoVetor] = valorSorteado;
                posicaoVetor++;
            }            
        }
    }
    
    //método responsável em apenas gerar valores de 0 á 60
    private int geraNumeros(){
        int valor = this.gerador.nextInt(61);
        return valor;
    }
    
    //Método criado para verificar se existe algum número repetido
    private int verificaNumerosRepetidos(int valor){        
        for(int i = 0; i < 6; i++){            
            if(valor == numeros[i]){
                return -1;
            }           
        }        
        return 0;
    }
    
}
